[Feature/iter5] Change priority for env, flags, default
skosovsky/metrics pull request #5
Opened 2024-05-15 10:13 UTC by skosovsky

Рефакторинг:
- изменил обработку env и названия полей
- небольшие изменения, в связи с заменой

2024-05-16 15:52 UTC, s-shpak commented on cmd/agent/main.go
> +	log "metrics/pkg/logger"
В Go не принято просто так давать псевдонимы экспортируемым пакетам

2024-05-16 15:54 UTC, s-shpak commented on cmd/agent/main.go
> +	_ = os.Setenv("APP_MODE", cfg.App.Mode)
Ошибки не надо игнорировать

2024-05-16 15:55 UTC, s-shpak commented on cmd/agent/main.go
> +	if os.Getenv("APP_MODE") == "test" || os.Getenv("APP_MODE") == "production" { //nolint:goconst // not applicable
Почему ? кажется, что замечание линтера правильное

2024-05-16 15:57 UTC, s-shpak commented on cmd/agent/main.go
> +		log.Fatal("appInfo", log.ErrAttr(err))
Фаталиться из глубины кода нельзя, см. видео https://app.pachca.com/chats/9180496?message=234290731

2024-05-16 15:58 UTC, s-shpak commented on config/config.go
> +		// Host string `env:"RCV_HOST"       validate:"required"`
deadcode

2024-05-16 15:59 UTC, s-shpak commented on config/config.go
> +		App
Зачем применять здесь композицию ?

2024-05-16 16:02 UTC, s-shpak commented on config/flags.go
> +	r.Address = flagValues[0] + ":" + flagValues[1]
Лучше использовать `fmt.Sprintf`

2024-05-16 16:08 UTC, s-shpak commented on config/config.go
> +	var configTransmitter Transmitter
Зачем создавать отдельные переменные, почему бы не писать сразу в `TransmitterConfig` ?

2024-05-16 16:12 UTC, s-shpak commented on cmd/server/main.go
> +	ctx := context.WithValue(context.Background(), receiver.KeyServiceCtx{}, metricsGetter)
1. Ключи лучше определять так: https://medium.com/@matryer/context-keys-in-go-5312346a868d
2. Не используй context как bag of values, здесь это не нужно. Передавай параметры либо через замыкания, либо (что лучше) через поля структуры

2024-05-16 16:13 UTC, s-shpak commented on cmd/agent/main.go
> +			log.Info("Updated metrics", log.AnyAttr("PollCount", statistics.PollCount))
Это будет засорять логи. Максимум - логировать это на уровне Debug

2024-05-16 16:14 UTC, s-shpak commented on cmd/agent/main.go
> +	statistics := transmitter.NewMetrics(cfg)
В Go принято давать переменным короткие имена

2024-05-16 16:16 UTC, s-shpak commented on internal/transmitter/transmitter.go
> +	metrics.gauges = append(metrics.gauges, model.Gauge{Name: "Alloc", Value: float64(memMetrics.Alloc)},
Может стоит просто вызвать Update при инициализации ?

2024-05-16 16:16 UTC, s-shpak commented on internal/transmitter/transmitter.go
> +			log.Warn("Unknown gauge metric: ", log.StringAttr("gauge name", gauge.Name))
Ошибки надо прокидывать наверх и решать там, что с ними делать

2024-05-16 16:17 UTC, s-shpak commented on internal/transmitter/transmitter.go
> +	length := len(m.PollCount)
Зачем делать `PollCounter` слайсом ? Сделай его просто `uint64`

2024-05-16 16:18 UTC, s-shpak commented on internal/transmitter/transmitter.go
> +	rnd := rand.New(rand.NewSource(time.Now().UnixNano())) //nolint:gosec // no sec
в `math/rand` в последних версиях встроена автоматическая рандомизация, это делать не нужно

2024-05-16 16:19 UTC, s-shpak commented on internal/transmitter/transmitter.go
> +func (m *Metrics) Clear() {
А зачем ?

2024-05-16 16:19 UTC, s-shpak commented on cmd/agent/main.go
> +			statistics.Clear()
Зачем ?

2024-05-16 16:19 UTC, s-shpak commented on internal/transmitter/transmitter.go
> +	m.Clear()
А зачем ?

2024-05-16 16:21 UTC, s-shpak commented on internal/transmitter/transmitter.go
> +			log.Warn("Unknown counter metric: ", log.StringAttr("counter name", poll.Name))
См. комментарий про ошибки

2024-05-16 16:22 UTC, s-shpak commented on internal/transmitter/transmitter.go
> +	if currentErrorRate := float64(countErr) / float64(len(urls)); currentErrorRate >= criticalErrorRate {
Не надо так делать, это не задача твоего кода, это задача системы мониторинга

2024-05-16 16:23 UTC, s-shpak commented on pkg/logger/logger.go
Я не понимаю, зачем ты все это делаешь. Все это уже реализовано из коробки в zap и т.п.

2024-05-16 16:24 UTC, s-shpak commented on pkg/logger/middleware.go
Этот файл не относится к логгеру, он должен относиться к `api`

2024-05-16 16:25 UTC, s-shpak commented on internal/store/dummy.go
Зачем это, если у тебя уже есть memory store, который просто настраивается для тестов ?

2024-05-16 16:26 UTC, s-shpak commented on internal/store/store.go
> +type Store interface {
Интерфейс определяется там, где используется

2024-05-16 16:26 UTC, s-shpak commented on cmd/server/main.go
> +	_ "modernc.org/sqlite"
Зачем это, если ты нигде не используешь `sqlite` ?

2024-05-16 16:29 UTC, s-shpak commented on internal/store/memory.go
> +func (m *MemoryStore) AddGauge(gauge model.Gauge) bool {
В го принято возвращать ошибки в таких случаях: то же самое, что `bool`, но более гибкие семантически

2024-05-16 16:30 UTC, s-shpak commented on internal/service/service.go
> +	log.Info("counters returned", log.AnyAttr("counters", counters))
Зачем это логирование ?

2024-05-16 16:31 UTC, s-shpak commented on internal/receiver/receiver.go
> +func HandlerMux() http.Handler {
deadcode

2024-05-16 16:31 UTC, s-shpak commented on internal/receiver/receiver_test.go
> +func TestRouting(t *testing.T) { // TODO: понять как же мы тут тестируем роутинг
deadcode. Тесты надо либо добавить, либо выпилить это

2024-05-16 16:32 UTC, s-shpak commented on internal/receiver/handlers.go
> +		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
`InternalServerError` надо логировать

2024-05-16 16:33 UTC, s-shpak commented on internal/receiver/handlers.go
> +		_, err = io.WriteString(w, strconv.Itoa(int(counterValues)))
Здесь потенциально возможно переполнение

2024-05-16 16:33 UTC, s-shpak commented on internal/receiver/handlers.go
> +			log.Error("Error writing response", log.ErrAttr(err)) //nolint:contextcheck // false positive
Что будет возвращено клиенту ?

2024-05-16 16:35 UTC, s-shpak requested changes
Настрой `golangci-lint` для запуска при помощи Github Actions, см. здесь как https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions. Поправь проблемы, которые линтер обнаружит

Обрати внимание, что я пометил не все проблемные места в коде: если одна и та же ошибка встречается несколько раз, то надо поправить ее везде

2024-05-17 04:52 UTC, skosovsky commented on cmd/agent/main.go
> +	log "metrics/pkg/logger"
Я не просто так это делаю:
- это  приятнее эстетически
- так я исключаю использование обычного логера 
- у нас в программе курса так же реализовано, см. Тема 1/4: Пакет log. Логирование в приложении → Урок 2/5 - Пакет logrus `log "github.com/sirupsen/logrus"`

2024-05-17 13:08 UTC, skosovsky commented on pkg/logger/logger.go
Потому что мне нравится slog. Я выбираю его.

2024-05-17 14:19 UTC, skosovsky commented on cmd/agent/main.go
> +	log "metrics/pkg/logger"
Я не просто так это делаю:
		- это  приятнее эстетически
		- так я исключаю использование обычного логера 
		- у нас в программе курса так же реализовано, см. Тема 1/4: Пакет log. Логирование в приложении → Урок 2/5 - Пакет logrus
```go
import (
    "os"

    log "github.com/sirupsen/logrus"
)

2024-05-17 14:25 UTC, skosovsky commented on config/flags.go
> +	r.Address = flagValues[0] + ":" + flagValues[1]
Не согласен, не лучше.

С этим не согласен не только я, использовать Sprintf - конкретно для Host:Port вредно, по 2 причинам:
1. Адрес может быть IPv6 и мы получим ошибку на ровном месте.
- линтер для этого - https://github.com/stbenjam/no-sprintf-host-port

2. Мы нагружаем GC и получаем низкую производительность
- линтер для этого: https://github.com/catenacyber/perfsprint

Специально потестил кейс:

Вот код к которому комментарий:
```go
r.Address = flagValues[0] + ":" + flagValues[1]
```

Вот 2 функции:
```go
func ConcatSprintf(values []string) string {  
    return fmt.Sprintf("%s:%s", values[0], values[1])  
}  
  
func ConcatPlus(values []string) string {  
    return values[0] + ":" + values[1]  
}
```

Вот тесты на них:
```go
func BenchmarkConcatPlus(b *testing.B) {  
    values := []string{"test1", "test2"}  
  
    for i := 0; i < b.N; i++ {  
       ConcatPlus(values)  
    }  
}  
  
func BenchmarkSprintf(b *testing.B) {  
    values := []string{"test1", "test2"}  
  
    for i := 0; i < b.N; i++ {  
       ConcatSprintf(values)  
    }  
}
```

Вот результаты:
```bash
BenchmarkConcatPlus-10   78910275   15.02 ns/op    0 B/op   0 allocs/op
BenchmarkSprintf-10      12795460   90.17 ns/op   48 B/op   3 allocs/op
```

2024-05-17 14:26 UTC, skosovsky commented on internal/transmitter/transmitter.go
> +	metrics.gauges = append(metrics.gauges, model.Gauge{Name: "Alloc", Value: float64(memMetrics.Alloc)},
нет, тогда нужно будет перебирать постоянно цикл, я не придумал оптимильнее решения, подскажите?

2024-05-17 14:26 UTC, skosovsky commented on internal/transmitter/transmitter.go
> +			log.Warn("Unknown gauge metric: ", log.StringAttr("gauge name", gauge.Name))
тут нет ошибки, это защита от ошибки, на случай, если я что-то руками исправлю в названиях при инициализации.

2024-05-17 14:27 UTC, skosovsky commented on internal/transmitter/transmitter.go
> +		url := "http://" + m.config.Address + "/update" + "/gauge/" + gauge.Name + "/" + strconv.FormatFloat(gauge.Value, 'f', -1, 64)
-  я поменяю конечно, потому что эстетически приятнее немного выглядит, но с точки зрения скорости это ад
```bash
BenchmarkPathJoin-10      2066823    573.8 ns/op   592 B/op   11 allocs/op
BenchmarkPathPlus-10   1000000000   0.3132 ns/op     0 B/op    0 allocs/op
```
- ради того чтобы слеши расставили и получить еще геморой с обработкой ошибки - вверх ее тянуть теперь...

2024-05-17 14:27 UTC, skosovsky commented on internal/store/dummy.go
- dummy - это store для юнит тестирования
	- позже добавлю fake - это как раз условно настроенный для тестов memory - но в следующий раз
	- memory store - это база, условный прод, я не могу ее для тестов использовать

2024-05-17 14:30 UTC, skosovsky commented
Замечания исправлены, за исключением тех, по которым я дал комментарии:
- комментарии указаны ответом к замечанию и продублированы в пачке

Спасибо за отличные замечания.

2024-05-21 13:04 UTC, s-shpak commented on cmd/agent/main.go
> +	log "metrics/pkg/logger"
1. Спорно
2. Для этого есть, например, `depguard`: https://github.com/OpenPeeDeeP/depguard
3. Не все практики, которые есть в учебнике, являются эталонными

Минус такого подхода в том, что код становится сложнее читать. Так что не стоит просто так давать псевдонимы пакетам

2024-05-21 13:08 UTC, s-shpak commented on internal/store/dummy.go
Почему ты не можешь использовать `memory store` для тестов ? В тестах, где используется memory store считается, что это хранилище уже протестировано и покрыто тестами, потому его можно и нужно использовать (плодить сущности хуже)

2024-05-21 13:26 UTC, s-shpak commented on internal/transmitter/transmitter.go
> +		url := "http://" + m.config.Address + "/update" + "/gauge/" + gauge.Name + "/" + strconv.FormatFloat(gauge.Value, 'f', -1, 64)
Это не вопрос эстетики. Вот аргументы за его исопльзование:

1. Попробуй понять, почему `url.JoinPath` возвращает ошибку
2. Не стоит заниматься преждевременной оптимизацией: лучше писать код просто и понятно. Оптимизировать можно будет, если мы поймем, что это действительно нужно

2024-05-21 13:26 UTC, s-shpak commented on internal/receiver/handlers.go
> +		answer += counter.Name + " " + strconv.FormatInt(counter.Value, 10) + "\n"
В этом случае, думаю, стоит использовать `string.Builder`

2024-05-21 13:30 UTC, s-shpak commented on internal/receiver/receiver.go
> +		return fmt.Errorf("could not start server: %w", err)
Сообщение об ошибке неправильное: ListenAndServe блокируется до преркащения работы сервера, так что ошибка может быть не связана с его запуском

2024-05-21 13:30 UTC, s-shpak commented on internal/receiver/run.go
> +		log.Fatal("run server",
Фаталиться из глубины кода нельзя

2024-05-21 13:36 UTC, s-shpak requested changes
См. комментарии

2024-05-21 14:20 UTC, skosovsky commented on internal/transmitter/transmitter.go
> +		url := "http://" + m.config.Address + "/update" + "/gauge/" + gauge.Name + "/" + strconv.FormatFloat(gauge.Value, 'f', -1, 64)
1. `url.JoinPath` возвращает ошибку в следующих случаях:
- `net/url: invalid control character in URL` - если в коде есть управляющие символы (это основной аргумент)
- `empty url` - если ссылка пустая
- `invalid URI for request` - если ссылка начинается с `/` или
- `first path segment in URL cannot contain colon` - это не понял, но тоже валидность url
2. Про оптимизацию понял. Выше написал что поменяю - в коде исправлено.

2024-05-21 14:52 UTC, skosovsky commented
Замечания исправлены, за исключением тех, по которым дал комментарии:
- комментарии указаны ответом к замечанию.

Никакие автотесты не запускаются - стоят в вечной очереди, но локально я все проверил, а сами изменения не касались логики.

2024-05-23 09:50 UTC, s-shpak requested changes

2024-05-23 09:50 UTC, s-shpak commented on internal/receiver/handlers.go
> +		answer += counter.Name + " " + strconv.FormatInt(counter.Value, 10) + "\n"
Надо, конечно, бенчить, но предполагаю, что в случае `prepareAllGauges` эффективность `string.Builder` будет выше: частая конактенация строк - дорогая операция

2024-05-23 12:18 UTC, skosovsky commented
Изменил структуру проекта, уменьшив связанность кода и снизив зависимости между приложениями.

Замечания также исправлены.
Оказывается WriteString - всегда пустую ошибку возвращает - поэтому не обрабатываю ее
```
func (b *Builder) WriteString(s string) (int, error) {
 b.copyCheck()
 b.buf = append(b.buf, s...)
 return len(s), nil
}
```

2024-05-23 18:51 UTC, s-shpak approved these changes

2024-05-24 02:34 UTC, merged