feat/iter-9: new file store and config for its
skosovsky/metrics pull request #9
Opened 2024-05-31 17:30 UTC by skosovsky

Добавлено для consumer:
- изменена структура хранения метрик
- файловое хранилище, все данные сохраняются в файл и восстанавливаются из файла, автосохранение
- изменены параметры конфигурации под него

2024-06-02 21:01 UTC, s-shpak requested changes

2024-06-03 05:00 UTC, skosovsky commented on internal/consumer/gzip.go
> +		g.WriteHeader(http.StatusOK)
У меня другая реализация middleware. Может быть стоит ее посмотреть, перед тем как писать замечание - я сохраняю себе тело - за меня это не сделает сервер.

2024-06-03 05:03 UTC, skosovsky commented on internal/consumer/gzip.go
> +	if g.statusCode == 0 {
Ну мы же должны записать заголовок 1 раз, второй раз он не даст сделать же... поэтому и не делает.

2024-06-03 05:06 UTC, skosovsky commented on internal/consumer/handlers.go
> +		http.Error(w, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)
Я незнаком с таким методом, не понимаю вопроса(

2024-06-03 06:00 UTC, skosovsky commented on internal/consumer/logs.go
> +			log.IntAttr("status", respData.statusCode),
Залогирутеся 0 статус, т.к. я ранее спрашивал о том как же сервер назначает статус (если он не назачен) и ты сказал, что он не использует WriteHeader. Что мне с этим делать я незнаю....

2024-06-03 06:00 UTC, skosovsky commented on internal/consumer/internal/store/memory.go
> +func (m *MemoryStore) AddCounter(counter service.Metric, increment bool) error {
Неясно - задал вопрос в пачке.

2024-06-04 15:00 UTC, skosovsky commented on internal/consumer/handlers.go
> +		http.Error(w, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)
BadRequest  у меня для другого - понятно что он делает тоже самое - это для роутера для всех других запросов - которые по ТЗ должны быть Bad Request. 

А метод тут использовать не к месту, нарушит единообразие остальных http.Error

2024-06-06 17:14 UTC, s-shpak commented on internal/consumer/handlers.go
> +func (h Handler) BadRequest(w http.ResponseWriter, _ *http.Request) {
1. Почему эта функция называется `BadRequest`, а  возвращает она `StatusNotFound` ?
2. Функции принято называть начиная с глагола, здесь не ясно, что делает эта функция
3. Вообще зачем создавать отдельную функцию для этого? Почему просто не создать анонимную функцию ?

2024-06-06 17:49 UTC, skosovsky commented
Все замечания исправлены.

2024-06-06 18:26 UTC, s-shpak approved these changes

2024-06-07 03:29 UTC, merged